class Selector
  def self.breed
    [
      "affenpinscher",
      "afghan hound",
      "afghan shepherd",
      "aidi",
      "airedale terrier",
      "akbash",
      "akita inu",
      "alano espaÃ±ol",
      "alaskan klee kai",
      "alaskan malamute",
      "alpine dachsbracke",
      "alpine spaniel",
      "american akita",
      "american bulldog",
      "american cocker spaniel",
      "american eskimo dog",
      "american foxhound",
      "american hairless terrier",
      "american pit bull terrier",
      "american staffordshire terrier",
      "american water spaniel",
      "anatolian shepherd dog",
      "andalusian hound",
      "anglo-franÃ§ais de petite vÃ©nerie",
      "appenzeller sennenhund",
      "ariege pointer",
      "ariegeois",
      "armant",
      "armenian gampr dog",
      "artois hound",
      "australian cattle dog",
      "australian kelpie",
      "australian shepherd",
      "australian silky terrier",
      "australian stumpy tail cattle dog[10]",
      "australian terrier",
      "austrian black and tan hound",
      "austrian pinscher",
      "azawakh",
      "bakharwal dog",
      "barbet",
      "basenji",
      "basque ratter",
      "basque shepherd dog",
      "basset artÃ©sien normand",
      "basset bleu de gascogne",
      "basset fauve de bretagne",
      "basset griffon vendÃ©en, grand",
      "basset griffon vendÃ©en, petit",
      "basset hound",
      "bavarian mountain hound",
      "beagle",
      "beagle-harrier",
      "bearded collie",
      "beauceron",
      "bedlington terrier",
      "belgian shepherd dog (groenendael)",
      "belgian shepherd dog (laekenois)",
      "belgian shepherd dog (malinois)",
      "belgian shepherd (tervuren)",
      "bergamasco shepherd",
      "berger blanc suisse",
      "berger picard",
      "berner laufhund",
      "bernese mountain dog",
      "bichon frisÃ©",
      "billy",
      "black and tan coonhound",
      "black and tan virginia foxhound",
      "black norwegian elkhound",
      "black russian terrier",
      "blackmouth cur",
      "bleu de gascogne, grand",
      "bleu de gascogne, petit",
      "bloodhound",
      "blue heeler",
      "blue lacy",
      "blue paul terrier",
      "bluetick coonhound",
      "boerboel",
      "bohemian shepherd",
      "bolognese",
      "border collie",
      "border terrier",
      "borzoi",
      "bosnian coarse-haired hound",
      "boston terrier",
      "bouvier des ardennes",
      "bouvier des flandres",
      "boxer",
      "boykin spaniel",
      "bracco italiano",
      "braque d'auvergne",
      "braque du bourbonnais",
      "braque du puy",
      "braque francais",
      "braque saint-germain",
      "brazilian dogo",
      "brazilian terrier",
      "briard",
      "briquet griffon vendÃ©en",
      "brittany",
      "broholmer",
      "bruno jura hound",
      "bucovina shepherd dog",
      "bull and terrier",
      "bull terrier",
      "bull terrier (miniature)",
      "bulldog",
      "bullenbeisser",
      "bullmastiff",
      "bully kutta",
      "burgos pointer",
      "cairn terrier",
      "canaan dog",
      "canadian eskimo dog",
      "cane corso",
      "cantabrian water dog",
      "cÃ£o da serra de aires",
      "cÃ£o de castro laboreiro",
      "cÃ£o fila de sÃ£o miguel",
      "carolina dog",
      "carpathian shepherd dog",
      "catahoula cur",
      "catalan sheepdog",
      "caucasian shepherd dog",
      "cavalier king charles spaniel",
      "central asian shepherd dog",
      "cesky fousek",
      "cesky terrier",
      "chesapeake bay retriever",
      "chien franÃ§ais blanc et noir",
      "chien franÃ§ais blanc et orange",
      "chien franÃ§ais tricolore",
      "chien-gris",
      "chihuahua",
      "chilean fox terrier",
      "chinese chongqing dog",
      "chinese crested dog",
      "chinese imperial dog",
      "chinook",
      "chippiparai",
      "chow chow",
      "cierny sery",
      "cirneco dell'etna",
      "clumber spaniel",
      "collie, rough",
      "collie, smooth",
      "combai",
      "cordoba fighting dog",
      "coton de tulear",
      "cretan hound",
      "croatian sheepdog",
      "cumberland sheepdog",
      "curly coated retriever",
      "cursinu",
      "czechoslovak wolfdog",
      "dachshund",
      "dalmatian",
      "dandie dinmont terrier",
      "danish swedish farmdog",
      "decker rat terrier",
      "deutsche bracke",
      "doberman pinscher",
      "dogo argentino",
      "dogo cubano",
      "dogue de bordeaux",
      "drentse patrijshond",
      "drever",
      "dunker",
      "dutch shepherd dog",
      "dutch smoushond",
      "east siberian laika",
      "east-european shepherd",
      "elo",
      "english cocker spaniel",
      "american english coonhound",
      "english foxhound",
      "english mastiff",
      "english setter",
      "english shepherd",
      "english springer spaniel",
      "english toy terrier (black & tan)",
      "english water spaniel",
      "english white terrier",
      "entlebucher mountain dog",
      "Ã©pagneul bleu de picardie",
      "estonian hound",
      "estrela mountain dog",
      "eurasier",
      "field spaniel",
      "fila brasileiro",
      "finnish hound",
      "finnish lapphund",
      "finnish spitz",
      "flat-coated retriever",
      "formosan mountain dog",
      "fox terrier (smooth)",
      "fox terrier, wire",
      "french brittany",
      "french bulldog",
      "french spaniel",
      "gaddi dog",
      "galgo espaÃ±ol",
      "galician cattle dog",
      "garafÃ­a shepherd dog",
      "gascon saintongeois",
      "georgian shepherd dog",
      "german longhaired pointer",
      "german pinscher",
      "german rough-haired pointer",
      "german shepherd dog",
      "german shorthaired pointer",
      "german spaniel",
      "german spitz",
      "german wirehaired pointer",
      "giant schnauzer",
      "glen of imaal terrier",
      "golden retriever",
      "gordon setter",
      "gran mastÃ­n de borÃ­nquen",
      "grand anglo-franÃ§ais blanc et noir",
      "grand anglo-franÃ§ais blanc et orange",
      "grand anglo-franÃ§ais tricolore",
      "grand griffon vendÃ©en",
      "great dane",
      "great pyrenees",
      "greater swiss mountain dog",
      "greek harehound",
      "greenland dog",
      "greyhound",
      "griffon bleu de gascogne",
      "griffon bruxellois",
      "griffon fauve de bretagne",
      "griffon nivernais",
      "guatemalan dogo",
      "hamiltonstÃ¶vare",
      "hanover hound",
      "hare indian dog",
      "harrier",
      "havanese",
      "hawaiian poi dog",
      "himalayan sheepdog",
      "hokkaido",
      "hortaya borzaya",
      "hovawart",
      "huntaway",
      "hygenhund",
      "ibizan hound",
      "icelandic sheepdog",
      "indian pariah dog",
      "indian spitz",
      "irish red and white setter",
      "irish setter",
      "irish terrier",
      "irish water spaniel",
      "irish wolfhound",
      "istrian coarse-haired hound",
      "istrian shorthaired hound",
      "italian greyhound",
      "jack russell terrier",
      "jagdterrier",
      "jÃ¤mthund",
      "japanese chin",
      "japanese spitz",
      "japanese terrier",
      "kaikadi",
      "kai ken",
      "kangal dog",
      "kanni",
      "karakachan dog",
      "karelian bear dog",
      "karst shepherd",
      "keeshond",
      "kerry beagle",
      "kerry blue terrier",
      "king charles spaniel",
      "king shepherd",
      "kintamani",
      "kishu",
      "komondor",
      "kooikerhondje",
      "koolie",
      "korean jindo dog",
      "kromfohrlÃ¤nder",
      "kumaon mastiff",
      "kunming wolfdog",
      "kurÄ«",
      "kuvasz",
      "kyi-leo",
      "labrador husky",
      "labrador retriever",
      "lagotto romagnolo",
      "lakeland terrier",
      "lancashire heeler",
      "landseer",
      "lapponian herder",
      "leonberger",
      "lhasa apso",
      "lithuanian hound",
      "longhaired whippet",
      "lÃ¶wchen",
      "magyar agÃ¡r",
      "mahratta greyhound",
      "majorca shepherd dog",
      "maltese",
      "manchester terrier",
      "maremma sheepdog",
      "mcnab",
      "mexican hairless dog",
      "miniature australian shepherd",
      "miniature american shepherd",
      "miniature fox terrier",
      "miniature pinscher",
      "miniature schnauzer",
      "miniature shar pei",
      "mioritic",
      "molossus",
      "montenegrin mountain hound",
      "moscow watchdog",
      "moscow water dog",
      "mountain cur",
      "mucuchies",
      "mudhol hound",
      "mudi",
      "mÃ¼nsterlÃ¤nder, large",
      "mÃ¼nsterlÃ¤nder, small",
      "neapolitan mastiff",
      "newfoundland",
      "new zealand heading dog",
      "norfolk spaniel",
      "norfolk terrier",
      "norrbottenspets",
      "north country beagle",
      "northern inuit dog",
      "norwegian buhund",
      "norwegian elkhound",
      "norwegian lundehund",
      "norwich terrier",
      "nova scotia duck-tolling retriever",
      "old croatian sighthound",
      "old danish pointer",
      "old english sheepdog",
      "old english terrier",
      "old german shepherd dog",
      "old time farm shepherd",
      "olde english bulldogge",
      "otterhound",
      "pachon navarro",
      "pandikona",
      "paisley terrier",
      "papillon",
      "parson russell terrier",
      "patterdale terrier",
      "pekingese",
      "perro de presa canario",
      "perro de presa mallorquin",
      "peruvian hairless dog",
      "phalÃ¨ne",
      "pharaoh hound",
      "phu quoc ridgeback dog",
      "picardy spaniel",
      "plott hound",
      "podenco canario",
      "pointer",
      "poitevin",
      "polish greyhound",
      "polish hound",
      "polish hunting dog",
      "polish lowland sheepdog",
      "polish tatra sheepdog",
      "pomeranian",
      "pont-audemer spaniel",
      "poodle",
      "porcelaine",
      "portuguese podengo",
      "portuguese pointer",
      "portuguese water dog",
      "posavac hound",
      "praÅ¾skÃ½ krysaÅ™Ã­k",
      "pudelpointer",
      "pug",
      "puli",
      "pumi",
      "pungsan dog",
      "pyrenean mastiff",
      "pyrenean shepherd",
      "rafeiro do alentejo",
      "rajapalayam",
      "rampur greyhound",
      "rastreador brasileiro",
      "ratonero bodeguero andaluz",
      "ratonero valenciano",
      "rat terrier",
      "redbone coonhound",
      "rhodesian ridgeback",
      "rottweiler",
      "russian spaniel",
      "russian toy",
      "russian tracker",
      "russo-european laika",
      "russell terrier",
      "saarlooswolfhond",
      "sabueso espaÃ±ol",
      "saint-usuge spaniel",
      "sakhalin husky",
      "saluki",
      "samoyed",
      "santal hound",
      "sapsali",
      "Å¡arplaninac",
      "schapendoes",
      "schillerstÃ¶vare",
      "schipperke",
      "standard schnauzer",
      "schweizer laufhund",
      "schweizerischer niederlaufhund",
      "scotch collie",
      "scottish deerhound",
      "scottish terrier",
      "sealyham terrier",
      "segugio italiano",
      "seppala siberian sleddog",
      "serbian hound",
      "serbian tricolour hound",
      "seskar seal dog",
      "shar pei",
      "shetland sheepdog",
      "shiba inu",
      "shih tzu",
      "shikoku",
      "shiloh shepherd dog",
      "siberian husky",
      "silken windhound",
      "sinhala hound",
      "skye terrier",
      "sloughi",
      "slovak cuvac",
      "slovakian rough-haired pointer",
      "slovenskÃ½ kopov",
      "smÃ¥landsstÃ¶vare",
      "small greek domestic dog",
      "soft-coated wheaten terrier",
      "south russian ovcharka",
      "southern hound",
      "spanish mastiff",
      "spanish water dog",
      "spinone italiano",
      "sporting lucas terrier",
      "st. bernard",
      "st. john's water dog",
      "stabyhoun",
      "staffordshire bull terrier",
      "stephens cur",
      "styrian coarse-haired hound",
      "sussex spaniel",
      "swedish lapphund",
      "swedish vallhund",
      "tahltan bear dog",
      "taigan",
      "talbot",
      "tamaskan dog",
      "teddy roosevelt terrier",
      "telomian",
      "tennessee treeing brindle",
      "tenterfield terrier",
      "terceira mastiff",
      "thai bangkaew dog",
      "thai ridgeback",
      "tibetan mastiff",
      "tibetan spaniel",
      "tibetan terrier",
      "tornjak",
      "tosa",
      "toy bulldog",
      "toy fox terrier",
      "toy manchester terrier",
      "toy trawler spaniel",
      "transylvanian hound",
      "treeing cur",
      "treeing walker coonhound",
      "trigg hound",
      "tweed water spaniel",
      "tyrolean hound",
      "uruguayan cimarron",
      "vanjari hound",
      "villano de las encartaciones",
      "vizsla",
      "volpino italiano",
      "weimaraner",
      "welsh corgi, cardigan",
      "welsh corgi, pembroke",
      "welsh sheepdog",
      "welsh springer spaniel",
      "welsh terrier",
      "west highland white terrier",
      "west siberian laika",
      "westphalian dachsbracke",
      "wetterhoun",
      "whippet",
      "white shepherd",
      "wirehaired pointing griffon",
      "wirehaired vizsla",
      "yorkshire terrier"
    ]
  end

  def self.breed_list
    breed.unshift("Breed")
  end

  def self.size
    ["Tiny: Less than 10 lbs", "Small: 10lbs - 30lbs", "Medium: 30lbs - 50lbs", "Large: Over 50lbs"]
  end

  def self.size_list
    size.unshift("Size")
  end

  def self.age
    ["Puppy: Less than a year", "Young: 1yr - 2yr", "Adult: 2yrs - 9yrs", "Senior: 10yrs and older"]
  end

  def self.age_list
    age.unshift("Age")
  end

  def self.gender
    ["Male", "Female"]
  end

  def self.gender_list
    gender.unshift("Gender")
  end

  def self.zipcodes
    [
      "80110",
      "80202",
      "80203",
      "80204",
      "80205",
      "80206",
      "80207",
      "80209",
      "80210",
      "80211",
      "80214",
      "80218",
      "80219",
      "80222",
      "80223",
      "80224",
      "80226",
      "80227",
      "80230",
      "80232",
      "80236",
      "80237",
      "80238",
      "80239",
      "80246",
      "80249",
      "80264",
      "80290",
      "80293",
      "80294"
    ]
  end
end
